FROM node:20-alpine AS build
ARG BUILD_TIMESTAMP
WORKDIR /app
COPY front/package*.json ./
RUN npm ci
COPY front/ .
RUN echo "Build timestamp: ${BUILD_TIMESTAMP}"
RUN npm run build -- --configuration production

FROM nginx:alpine
# gettext pour envsubst
RUN apk add --no-cache gettext
COPY --from=build /app/dist/front/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY start.sh /start.sh
RUN chmod +x /start.sh
EXPOSE 80
CMD ["/start.sh"]