# ===== Stage 1 : Build Angular =====
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG BUILD_TIMESTAMP
RUN echo "Build timestamp: ${BUILD_TIMESTAMP}"
RUN npm run build -- --configuration production

# ===== Stage 2 : nginx =====
FROM nginx:alpine
RUN apk add --no-cache gettext dos2unix

COPY --from=build /app/dist/front/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Corrige les fins de ligne Windows (CRLF -> LF) qui cassent le parsing nginx
RUN dos2unix /etc/nginx/conf.d/default.conf

COPY start.sh /start.sh
RUN dos2unix /start.sh && chmod +x /start.sh

ENTRYPOINT ["/start.sh"]